### ISSUE TITLE
Reduce the output of command to reduce processing

### ISSUE THREAD

**Issue by hepabolu** [DaniBarca/CPU-Usage-bar-Widget#1]
As far as I can tell your command outputs multiple lines of the 'top' command, while you only process the line that starts with 'CPU usage'. 

Wouldn't it be better to modify the command to `"top -u -l -1 | grep 'CPU usage'"` and process only that line?

**Comment by DaniBarca** [comment]
Hi, hepabolu, you might be talking of another project because the code doesn't do what you say.

The command being used is:
`ps aux  | awk 'BEGIN { sum = 0 }  { sum += $3 }; END { print sum }' && sysctl hw.ncpu | awk '{print $2}'`

This command outputs two lines: the first one, with the percentage of CPU being used, and the second one with the number of cores that are available to the OS.

Anyway, feel free to modify the code if you want.

**Comment by hepabolu** [comment]
I guess you're right. It must be another project. Sorry.
